"""posts table

Revision ID: e8f7aeaa4fae
Revises: d0aa9aa2bbed
Create Date: 2018-11-21 16:36:56.372398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f7aeaa4fae'
down_revision = 'd0aa9aa2bbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('status_prist', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'status_prist')
    # ### end Alembic commands ###
